### ISSUE TITLE
Install "{{ cli_dependencies_packages }}" dependencies required root privilege

### ISSUE THREAD

**Issue by cloudBuddy77** [christiangda/ansible-role-awscli#7]
Hey Christian,

The task `TASK [awscli : Install "['python3-pip', 'python3-pysocks']" dependencies]` needs to be run by "root" user. I dont see a become flag in the task which will enable this.

This is the error I get:
TASK [awscli : Install "['python3-pip', 'python3-pysocks']" dependencies] *******************************************************************
FAILED - RETRYING: Install "['python3-pip', 'python3-pysocks']" dependencies (5 retries left).
FAILED - RETRYING: Install "['python3-pip', 'python3-pysocks']" dependencies (4 retries left).
FAILED - RETRYING: Install "['python3-pip', 'python3-pysocks']" dependencies (3 retries left).
FAILED - RETRYING: Install "['python3-pip', 'python3-pysocks']" dependencies (2 retries left).
FAILED - RETRYING: Install "['python3-pip', 'python3-pysocks']" dependencies (1 retries left).
fatal: [<host_name>]: FAILED! => {"attempts": 5, "changed": false, "msg": "This command has to be run under the root user.", "results": []}

Should we add a become flag for this task or am I wrong somewhere?

Thanks,
Avinash

**Comment by cloudBuddy77** [comment]
Same is needed for the `Install {{ cli_package }}` as this is installed using `pip` and pip needs to be run as sudo

**Comment by jlosito** [comment]
> Should we add a become flag for this task or am I wrong somewhere?

You can add the `become` at the playbook level. There's a lot of roles which don't have the `become` apart of a task which needs elevated privileges. It's pretty inconsistent across roles from my experience.

**Comment by christiangda** [comment]
thanks for your answer @jlosito

**Comment by christiangda** [comment]
@cloudBuddy77 I going to close this because the privileged access is not needed at the package level
